### ISSUE TITLE
Collapse for non-package mode

### ISSUE THREAD

**Issue by dgrigonis** [mgedmin/findimports#25]
What I would like is to be able to control collapse of sub-packages individually for external dependencies and non-external dependencies in non-package mode.

Maybe there is an easy way to implement it?

By the way.
Nicely written package. This is my goto option for dependency graphs now. Although it's simpler than some alternatives, but it is nicely written and works fast.

Also,
I was just wandering if any work is planned on making nicer outputs for `graphviz` and/or clustering.

**Comment by mgedmin** [comment]
I have no concrete plans beyond adding support for new Python versions and keeping the tests running.

TBH I don't fully trust the correctness of the output, especially on code that uses partially-qualified module names like `from pkg import sub; import pkg.sub.sub; x = sub.sub.some_fn()`.
