### ISSUE TITLE
To all contributors: Approval request for changing license. GPL -> MIT

### ISSUE THREAD

**Issue by dgrigonis** [mgedmin/findimports#27]
Hello all contributors,

It can be seen that there were considerations for MIT license in the beginning of development of this library. However, it was licensed under GPL.

I have raised a request to the owner of this library regarding license change and he has kindly agreed.

However, for this to happen approval is needed from every non-trivial contributor.

_Implications fo this change are as follow:_
* All new versions are simply licensed under the new license.
* Anyone who needs code licensed under the old license (GPL) can fork the earlier version.

**So I am raising this issue for contributors to approve (or not) this request for license change.**

Approvals needed for this to happen:
1. @mgedmin
2. @Nicolas-Reyland 

Approvals that would make this transition easier:
3. @takos22 
4. @jepler 
5. @zzzeek 
6. @timhoffm

It would be much help if contributors commented their position in this issue.

Regards,
Dominykas

**Comment by jepler** [comment]
My previous contributions to this git repository may be used under the MIT license.

**Comment by Nicolas-Reyland** [comment]
My previous contributions to this git repository may be used under the MIT license.

**Comment by zzzeek** [comment]
i approve my contribution to the MIT license

no idea why i was even using this package ten years ago...

**Comment by takos22** [comment]
My previous contributions to this git repository may be used under the MIT license.

**Comment by mgedmin** [comment]
Thank you, everyone!

**Comment by mgedmin** [comment]
I think we're missing only @timhoffm's agreement (see PRs #20, #21), and then we can switch findimports's licence to MIT.

**Comment by timhoffm** [comment]
My previous contributions to this git repository may be used under the MIT license.

**Comment by dgrigonis** [comment]
Thank you all.
